name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      uploadAssets:
        description: 'Upload Assets'
        type: boolean
        required: false
        default: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - run: npm install

    - run: npm run prebuildify-${{ matrix.os }}

    - run: npm run prebuildify-upload -- ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event.inputs.uploadAssets != 'false' }}